apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests/common/istio-1-14/istio-crds/base
  - ../manifests/common/istio-1-14/istio-namespace/base
  - ../manifests/common/istio-1-14/istio-install/base
