apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
  - ../manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio
