apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests/common/kubeflow-namespace/base
  - ../manifests/common/kubeflow-roles/base
  - ../manifests/common/istio-1-11/kubeflow-istio-resources/base
  - ../manifests/apps/kfserving/upstream/overlays/kubeflow
  - ../manifests/apps/centraldashboard/upstream/overlays/istio
  - ../manifests/apps/admission-webhook/upstream/overlays/cert-manager
  - ../manifests/apps/profiles/upstream/overlays/kubeflow
  - ../manifests/apps/volumes-web-app/upstream/overlays/istio
  - ../manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
  - ../manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
  - ../manifests/apps/training-operator/upstream/overlays/kubeflow
  - ../manifests/common/user-namespace/base
