apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Cert-Manager
#- https://github.com/kubeflow/manifests/common/cert-manager/cert-manager/base?ref=v1.7.0
- https://github.com/kubeflow/manifests/common/cert-manager/kubeflow-issuer/base?ref=v1.7.0
# Istio
- https://github.com/kubeflow/manifests/common/istio-1-16/istio-crds/base?ref=v1.7.0
- https://github.com/kubeflow/manifests/common/istio-1-16/istio-namespace/base?ref=v1.7.0
- https://github.com/kubeflow/manifests/common/istio-1-16/istio-install/base?ref=v1.7.0
# OIDC Authservice
- https://github.com/kubeflow/manifests/common/oidc-authservice/base?ref=v1.7.0
# Dex
- https://github.com/kubeflow/manifests/common/dex/overlays/istio?ref=v1.7.0
# KNative
- https://github.com/kubeflow/manifests/common/knative/knative-serving/overlays/gateways?ref=v1.7.0
- https://github.com/kubeflow/manifests/common/knative/knative-eventing/base?ref=v1.7.0
- https://github.com/kubeflow/manifests/common/istio-1-16/cluster-local-gateway/base?ref=v1.7.0
# Kubeflow namespace
- https://github.com/kubeflow/manifests/common/kubeflow-namespace/base?ref=v1.7.0
# Kubeflow Roles
- https://github.com/kubeflow/manifests/common/kubeflow-roles/base?ref=v1.7.0
# Kubeflow Istio Resources
- https://github.com/kubeflow/manifests/common/istio-1-16/kubeflow-istio-resources/base?ref=v1.7.0


# Kubeflow Pipelines
- https://github.com/kubeflow/manifests/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user?ref=v1.7.0
# Katib
- https://github.com/kubeflow/manifests/apps/katib/upstream/installs/katib-with-kubeflow?ref=v1.7.0
# Central Dashboard
- https://github.com/kubeflow/manifests/apps/centraldashboard/upstream/overlays/kserve?ref=v1.7.0
# Admission Webhook
- https://github.com/kubeflow/manifests/apps/admission-webhook/upstream/overlays/cert-manager?ref=v1.7.0
# Jupyter Web App
- https://github.com/kubeflow/manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio?ref=v1.7.0
# Notebook Controller
- https://github.com/kubeflow/manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=v1.7.0
# Profiles + KFAM
- https://github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=v1.7.0
# Volumes Web App
- https://github.com/kubeflow/manifests/apps/volumes-web-app/upstream/overlays/istio?ref=v1.7.0
# Tensorboards Controller
- https://github.com/kubeflow/manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow?ref=v1.7.0
# Tensorboard Web App
- https://github.com/kubeflow/manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio?ref=v1.7.0
# Training Operator
- https://github.com/kubeflow/manifests/apps/training-operator/upstream/overlays/kubeflow?ref=v1.7.0
# User namespace
- https://github.com/kubeflow/manifests/common/user-namespace/base?ref=v1.7.0

# KServe
- https://github.com/kubeflow/manifests/contrib/kserve/kserve?ref=v1.7.0
- https://github.com/kubeflow/manifests/contrib/kserve/models-web-app/overlays/kubeflow?ref=v1.7.0