apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-knative
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: knative-serving
    server: https://kubernetes.default.svc
  project: datalab-project
  source:
    path: kubeflow-knative
    repoURL: https://github.com/tom333/argocd-kubeflow.git
    targetRevision: HEAD
    kustomize:
      version: v3.2.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - .rules
